## DATA
# DATA PATH
DATA: lung_cancer.db

# VARIABLES AND FEATURES
TARGET_VARIABLE: Lung Cancer Occurrence

CATERGORICAL_FEATURES:
  - 'Gender'
  - 'COPD History'
  - 'Genetic Markers'
  - 'Air Pollution Exposure'
  - 'Taken Bronchodilators'
  - 'Frequency of Tiredness'
  - 'Dominant Hand'

NUMERICAL_FEATURES:
  - 'Age'
  - 'Last Weight'
  - 'Current Weight'

DROP_FEATURES:
  - 'ID'
  - 'Start Smoking'
  - 'Stop Smoking'

## IMPUTATION
IMPUTE_MEDIAN: 
 - 'Age'

IMPUTE_MODE:
  - 'Gender'
  - 'Genetic Markers'
  - 'Air Pollution Exposure'
  - 'Frequency of Tiredness'
  - 'Dominant Hand'

IMPUTE_REFERENCE:
  - - 'Current Weight'
    - 'Last Weight'
  - - 'COPD History'
    - 'Taken Bronchodilators'

## MODELLING
# TRAIN_VALIDATE_TEST_SPLIT SIZE
TEST_SIZE: 0.1
VALIDATION_SIZE: 0.2

# FIX SEED
SEED: 2024

# HYPERPARAMETERS