## DATA
# DATA PATH
DATA: lung_cancer.db
QUERY: SELECT * FROM lung_cancer

# VARIABLES AND FEATURES
TARGET_VARIABLE: Lung Cancer Occurrence

CATEGORICAL_FEATURES:
  - 'Gender'
  - 'COPD History'
  - 'Genetic Markers'
  - 'Air Pollution Exposure'
  - 'Taken Bronchodilators'
  - 'Frequency of Tiredness'
  - 'Dominant Hand'

NUMERICAL_FEATURES:
  - 'Age'
  - 'Last Weight'
  - 'Current Weight'

DROP_FEATURES:
  - 'ID'
  - 'Start Smoking'
  - 'Stop Smoking'
  - 'Current Weight'
  - 'Last Weight'

## IMPUTATION
IMPUTE_MEDIAN: 
  - 'Age'

IMPUTE_MODE:
  - 'Gender'
  - 'Genetic Markers'
  - 'Air Pollution Exposure'
  - 'Frequency of Tiredness'
  - 'Dominant Hand'

IMPUTE_REFERENCE:
  - - 'Current Weight'
    - 'Last Weight'
  - - 'COPD History'
    - 'Taken Bronchodilators'

## ENCODING
NOMINAL_CATEGORICAL:
  - 'Gender'
  - 'COPD History'
  - 'Genetic Markers'
  - 'Taken Bronchodilators'
  - 'Dominant Hand'

ORDINAL_CATEGORICAL:
  - 'Air Pollution Exposure'
  - 'Frequency of Tiredness'
  - 'Cat Smoker'

## MODELLING
# MODEL
MODEL_SELECTION: 'LGBMClassifier'
MODEL_VERSION: '01'

# TRAIN_VALIDATE_TEST_SPLIT SIZE
TEST_SIZE: 0.1
VALIDATION_SIZE: 0.2

# FIX SEED
SEED: 2024

# HYPERPARAMETERS
CV: 5
TUNING_GRID:
  model__learning_rate:
    - 0.001
    - 0.003
    - 0.1
  model__n_estimators: 
    - 50
    - 250
    - 500
  model__num_leaves:
    - 5
    - 15
    - 31

LGBM_STR_HPARAMS:
  metric: 'binary_logloss'

LGBM_INT_HPARAMS:
  n_estimators: 500
  bagging_freq: 1
  num_leaves: 6
  min_data_in_leaf: 2

LGBM_FLOAT_HPARAMS:
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.7